// ── Symbol search (混合策略: 美股本地数据库 + 加密货币 CoinGecko) ──

interface SearchResult {
  symbol: string;
  name: string;
}

// ── 美股: 标普500 + 纳斯达克 + 热门中概 + 知名个股（本地搜索，无需 API） ──

const US_STOCKS: SearchResult[] = [
  { symbol: 'AAPL', name: 'Apple Inc.' },
  { symbol: 'MSFT', name: 'Microsoft Corporation' },
  { symbol: 'GOOGL', name: 'Alphabet Inc. (Google)' },
  { symbol: 'AMZN', name: 'Amazon.com Inc.' },
  { symbol: 'NVDA', name: 'NVIDIA Corporation' },
  { symbol: 'META', name: 'Meta Platforms Inc.' },
  { symbol: 'TSLA', name: 'Tesla Inc.' },
  { symbol: 'BRK.B', name: 'Berkshire Hathaway' },
  { symbol: 'JPM', name: 'JPMorgan Chase & Co.' },
  { symbol: 'V', name: 'Visa Inc.' },
  { symbol: 'JNJ', name: 'Johnson & Johnson' },
  { symbol: 'WMT', name: 'Walmart Inc.' },
  { symbol: 'MA', name: 'Mastercard Inc.' },
  { symbol: 'PG', name: 'Procter & Gamble Co.' },
  { symbol: 'UNH', name: 'UnitedHealth Group Inc.' },
  { symbol: 'HD', name: 'Home Depot Inc.' },
  { symbol: 'BAC', name: 'Bank of America Corp.' },
  { symbol: 'DIS', name: 'Walt Disney Co.' },
  { symbol: 'ADBE', name: 'Adobe Inc.' },
  { symbol: 'NFLX', name: 'Netflix Inc.' },
  { symbol: 'CRM', name: 'Salesforce Inc.' },
  { symbol: 'AMD', name: 'Advanced Micro Devices' },
  { symbol: 'INTC', name: 'Intel Corporation' },
  { symbol: 'QCOM', name: 'QUALCOMM Inc.' },
  { symbol: 'TXN', name: 'Texas Instruments Inc.' },
  { symbol: 'AVGO', name: 'Broadcom Inc.' },
  { symbol: 'COST', name: 'Costco Wholesale Corp.' },
  { symbol: 'PEP', name: 'PepsiCo Inc.' },
  { symbol: 'KO', name: 'Coca-Cola Company' },
  { symbol: 'ABBV', name: 'AbbVie Inc.' },
  { symbol: 'MRK', name: 'Merck & Co. Inc.' },
  { symbol: 'PFE', name: 'Pfizer Inc.' },
  { symbol: 'LLY', name: 'Eli Lilly and Company' },
  { symbol: 'TMO', name: 'Thermo Fisher Scientific' },
  { symbol: 'NKE', name: 'Nike Inc.' },
  { symbol: 'MCD', name: "McDonald's Corporation" },
  { symbol: 'SBUX', name: 'Starbucks Corporation' },
  { symbol: 'UBER', name: 'Uber Technologies Inc.' },
  { symbol: 'PYPL', name: 'PayPal Holdings Inc.' },
  { symbol: 'SNAP', name: 'Snap Inc.' },
  { symbol: 'BA', name: 'Boeing Company' },
  { symbol: 'CAT', name: 'Caterpillar Inc.' },
  { symbol: 'GE', name: 'General Electric Company' },
  { symbol: 'IBM', name: 'International Business Machines' },
  { symbol: 'ORCL', name: 'Oracle Corporation' },
  { symbol: 'CSCO', name: 'Cisco Systems Inc.' },
  { symbol: 'CVX', name: 'Chevron Corporation' },
  { symbol: 'XOM', name: 'Exxon Mobil Corporation' },
  { symbol: 'COP', name: 'ConocoPhillips' },
  { symbol: 'TSM', name: 'Taiwan Semiconductor Manufacturing' },
  { symbol: 'ASML', name: 'ASML Holding N.V.' },
  { symbol: 'SHEL', name: 'Shell plc' },
  { symbol: 'TM', name: 'Toyota Motor Corporation' },
  { symbol: 'BABA', name: 'Alibaba Group Holding Ltd.' },
  { symbol: 'PDD', name: 'PDD Holdings Inc.' },
  { symbol: 'JD', name: 'JD.com Inc.' },
  { symbol: 'NIO', name: 'NIO Inc.' },
  { symbol: 'PLTR', name: 'Palantir Technologies Inc.' },
  { symbol: 'SNOW', name: 'Snowflake Inc.' },
  { symbol: 'ZM', name: 'Zoom Video Communications' },
  { symbol: 'SQ', name: 'Block Inc.' },
  { symbol: 'SHOP', name: 'Shopify Inc.' },
  { symbol: 'SPOT', name: 'Spotify Technology S.A.' },
  { symbol: 'ABNB', name: 'Airbnb Inc.' },
  { symbol: 'DASH', name: 'DoorDash Inc.' },
  { symbol: 'COIN', name: 'Coinbase Global Inc.' },
  { symbol: 'RBLX', name: 'Roblox Corporation' },
  { symbol: 'LCID', name: 'Lucid Group Inc.' },
  { symbol: 'RIVN', name: 'Rivian Automotive Inc.' },
  { symbol: 'ARM', name: 'Arm Holdings plc' },
  { symbol: 'SMCI', name: 'Super Micro Computer Inc.' },
  { symbol: 'MU', name: 'Micron Technology Inc.' },
  { symbol: 'AMAT', name: 'Applied Materials Inc.' },
  { symbol: 'LRCX', name: 'Lam Research Corporation' },
  { symbol: 'KLAC', name: 'KLA Corporation' },
  { symbol: 'NOW', name: 'ServiceNow Inc.' },
  { symbol: 'INTU', name: 'Intuit Inc.' },
  { symbol: 'ISRG', name: 'Intuitive Surgical Inc.' },
  { symbol: 'SPGI', name: 'S&P Global Inc.' },
  { symbol: 'GS', name: 'Goldman Sachs Group Inc.' },
  { symbol: 'MS', name: 'Morgan Stanley' },
  { symbol: 'BLK', name: 'BlackRock Inc.' },
  { symbol: 'C', name: 'Citigroup Inc.' },
  { symbol: 'WFC', name: 'Wells Fargo & Company' },
  { symbol: 'AXP', name: 'American Express Company' },
  { symbol: 'VZ', name: 'Verizon Communications Inc.' },
  { symbol: 'T', name: 'AT&T Inc.' },
  { symbol: 'TMUS', name: 'T-Mobile US Inc.' },
  { symbol: 'CMCSA', name: 'Comcast Corporation' },
  { symbol: 'UPS', name: 'United Parcel Service Inc.' },
  { symbol: 'FDX', name: 'FedEx Corporation' },
  { symbol: 'LMT', name: 'Lockheed Martin Corporation' },
  { symbol: 'RTX', name: 'RTX Corporation' },
  { symbol: 'HON', name: 'Honeywell International Inc.' },
  { symbol: 'DE', name: 'Deere & Company' },
  { symbol: 'MMM', name: '3M Company' },
  { symbol: 'LIN', name: 'Linde plc' },
  { symbol: 'UNP', name: 'Union Pacific Corporation' },
  { symbol: 'NEE', name: 'NextEra Energy Inc.' },
  { symbol: 'SO', name: 'Southern Company' },
  { symbol: 'DUK', name: 'Duke Energy Corporation' },
  { symbol: 'D', name: 'Dominion Energy Inc.' },
  { symbol: 'O', name: 'Realty Income Corporation' },
  { symbol: 'SPG', name: 'Simon Property Group Inc.' },
  { symbol: 'AMT', name: 'American Tower Corporation' },
  { symbol: 'PLD', name: 'Prologis Inc.' },
  { symbol: 'CCI', name: 'Crown Castle Inc.' },
  { symbol: 'ADP', name: 'Automatic Data Processing Inc.' },
  { symbol: 'FI', name: 'Fiserv Inc.' },
  { symbol: 'BX', name: 'Blackstone Inc.' },
  { symbol: 'SCHW', name: 'Charles Schwab Corporation' },
  { symbol: 'CB', name: 'Chubb Limited' },
  { symbol: 'MMC', name: 'Marsh & McLennan Companies' },
  { symbol: 'AON', name: 'Aon plc' },
  { symbol: 'ELV', name: 'Elevance Health Inc.' },
  { symbol: 'CI', name: 'Cigna Group' },
  { symbol: 'HUM', name: 'Humana Inc.' },
  { symbol: 'ZTS', name: 'Zoetis Inc.' },
  { symbol: 'BMY', name: 'Bristol-Myers Squibb Company' },
  { symbol: 'GILD', name: 'Gilead Sciences Inc.' },
  { symbol: 'AMGN', name: 'Amgen Inc.' },
  { symbol: 'REGN', name: 'Regeneron Pharmaceuticals Inc.' },
  { symbol: 'VRTX', name: 'Vertex Pharmaceuticals Inc.' },
  { symbol: 'BSX', name: 'Boston Scientific Corporation' },
  { symbol: 'SYK', name: 'Stryker Corporation' },
  { symbol: 'MDT', name: 'Medtronic plc' },
  { symbol: 'EW', name: 'Edwards Lifesciences Corp.' },
  { symbol: 'ABT', name: 'Abbott Laboratories' },
  { symbol: 'DHR', name: 'Danaher Corporation' },
  { symbol: 'TJX', name: 'TJX Companies Inc.' },
  { symbol: 'LOW', name: "Lowe's Companies Inc." },
  { symbol: 'ORLY', name: "O'Reilly Automotive Inc." },
  { symbol: 'AZO', name: 'AutoZone Inc.' },
  { symbol: 'MAR', name: 'Marriott International Inc.' },
  { symbol: 'HLT', name: 'Hilton Worldwide Holdings Inc.' },
  { symbol: 'BKNG', name: 'Booking Holdings Inc.' },
  { symbol: 'BB', name: 'BlackBerry Limited' },
  { symbol: 'GME', name: 'GameStop Corp.' },
  { symbol: 'AMC', name: 'AMC Entertainment Holdings' },
  { symbol: 'BBBY', name: 'Bed Bath & Beyond Inc.' },
  { symbol: 'HOOD', name: 'Robinhood Markets Inc.' },
  { symbol: 'SOFI', name: 'SoFi Technologies Inc.' },
  { symbol: 'AFRM', name: 'Affirm Holdings Inc.' },
  { symbol: 'F', name: 'Ford Motor Company' },
  { symbol: 'GM', name: 'General Motors Company' },
  { symbol: 'XPEV', name: 'XPeng Inc.' },
  { symbol: 'LI', name: 'Li Auto Inc.' },
  { symbol: 'BYDDY', name: 'BYD Company Limited' },
  { symbol: 'TWLO', name: 'Twilio Inc.' },
  { symbol: 'DKNG', name: 'DraftKings Inc.' },
  { symbol: 'PINS', name: 'Pinterest Inc.' },
  { symbol: 'ETSY', name: 'Etsy Inc.' },
  { symbol: 'U', name: 'Unity Software Inc.' },
  { symbol: 'NET', name: 'Cloudflare Inc.' },
  { symbol: 'DDOG', name: 'Datadog Inc.' },
  { symbol: 'CRWD', name: 'CrowdStrike Holdings Inc.' },
  { symbol: 'ZS', name: 'Zscaler Inc.' },
  { symbol: 'OKTA', name: 'Okta Inc.' },
  { symbol: 'MDB', name: 'MongoDB Inc.' },
  { symbol: 'TEAM', name: 'Atlassian Corporation' },
  { symbol: 'TTD', name: 'The Trade Desk Inc.' },
  { symbol: 'WDAY', name: 'Workday Inc.' },
  { symbol: 'MRVL', name: 'Marvell Technology Inc.' },
  { symbol: 'ON', name: 'ON Semiconductor Corporation' },
  { symbol: 'MPWR', name: 'Monolithic Power Systems' },
  { symbol: 'PANW', name: 'Palo Alto Networks Inc.' },
  { symbol: 'FTNT', name: 'Fortinet Inc.' },
  { symbol: 'ENPH', name: 'Enphase Energy Inc.' },
  { symbol: 'FSLR', name: 'First Solar Inc.' },
  { symbol: 'PLUG', name: 'Plug Power Inc.' },
  { symbol: 'FCEL', name: 'FuelCell Energy Inc.' },
  { symbol: 'MRNA', name: 'Moderna Inc.' },
  { symbol: 'BNTX', name: 'BioNTech SE' },
  { symbol: 'CVNA', name: 'Carvana Co.' },
  { symbol: 'W', name: 'Wayfair Inc.' },
  { symbol: 'CHWY', name: 'Chewy Inc.' },
  { symbol: 'ROKU', name: 'Roku Inc.' },
  { symbol: 'MSTR', name: 'MicroStrategy Incorporated' },
  { symbol: 'MARA', name: 'Marathon Digital Holdings' },
  { symbol: 'RIOT', name: 'Riot Platforms Inc.' },
  { symbol: 'CLSK', name: 'CleanSpark Inc.' },
  { symbol: 'BITF', name: 'Bitfarms Ltd.' },
  { symbol: 'HUT', name: 'Hut 8 Corp.' },
  { symbol: 'SOUN', name: 'SoundHound AI Inc.' },
  { symbol: 'AI', name: 'C3.ai Inc.' },
  { symbol: 'BBAI', name: 'BigBear.ai Holdings Inc.' },
  { symbol: 'IONQ', name: 'IonQ Inc.' },
  { symbol: 'QBTS', name: 'D-Wave Quantum Inc.' },
  { symbol: 'RGTI', name: 'Rigetti Computing Inc.' },
  { symbol: 'ASTS', name: 'AST SpaceMobile Inc.' },
  { symbol: 'LUNR', name: 'Intuitive Machines Inc.' },
  { symbol: 'RKLB', name: 'Rocket Lab USA Inc.' },
  { symbol: 'ACHR', name: 'Archer Aviation Inc.' },
  { symbol: 'JOBY', name: 'Joby Aviation Inc.' },
  { symbol: 'NU', name: 'Nu Holdings Ltd.' },
  { symbol: 'CELH', name: 'Celsius Holdings Inc.' },
  { symbol: 'DECK', name: 'Deckers Outdoor Corporation' },
  { symbol: 'VRT', name: 'Vertiv Holdings Co.' },
  { symbol: 'AXON', name: 'Axon Enterprise Inc.' },
  { symbol: 'APP', name: 'AppLovin Corporation' },
  { symbol: 'DUOL', name: 'Duolingo Inc.' },
  { symbol: 'CAVA', name: 'CAVA Group Inc.' },
  { symbol: 'CART', name: 'Instacart (Maplebear Inc.)' },
  { symbol: 'RDDT', name: 'Reddit Inc.' },
  { symbol: 'DJT', name: 'Trump Media & Technology Group' },
  { symbol: 'TLT', name: 'iShares 20+ Year Treasury Bond ETF' },
  { symbol: 'SPY', name: 'SPDR S&P 500 ETF Trust' },
  { symbol: 'QQQ', name: 'Invesco QQQ Trust' },
  { symbol: 'IWM', name: 'iShares Russell 2000 ETF' },
  { symbol: 'DIA', name: 'SPDR Dow Jones Industrial Average ETF' },
  { symbol: 'VOO', name: 'Vanguard S&P 500 ETF' },
  { symbol: 'VTI', name: 'Vanguard Total Stock Market ETF' },
  { symbol: 'ARKK', name: 'ARK Innovation ETF' },
  { symbol: 'SOXX', name: 'iShares Semiconductor ETF' },
  { symbol: 'SMH', name: 'VanEck Semiconductor ETF' },
  { symbol: 'XLF', name: 'Financial Select Sector SPDR' },
  { symbol: 'XLE', name: 'Energy Select Sector SPDR' },
  { symbol: 'GLD', name: 'SPDR Gold Shares' },
  { symbol: 'SLV', name: 'iShares Silver Trust' },
  { symbol: 'IBIT', name: 'iShares Bitcoin Trust' },
  { symbol: 'FBTC', name: 'Fidelity Wise Origin Bitcoin Fund' },
  { symbol: 'ETHU', name: '2x Ether ETF' },
];

/** 本地搜索美股（代码和名称均可搜） */
export function searchStocks(query: string): SearchResult[] {
  const q = query.toLowerCase();
  if (q.length < 1) return [];
  return US_STOCKS
    .filter((s) =>
      s.symbol.toLowerCase().includes(q) ||
      s.name.toLowerCase().includes(q)
    )
    .slice(0, 8);
}

// ── 加密货币: CoinGecko（免费 API，支持 CORS） ──

/** 通过 CoinGecko 在线搜索加密货币 */
export async function searchCrypto(query: string): Promise<SearchResult[]> {
  if (query.length < 1) return [];
  try {
    const res = await fetch(
      `https://api.coingecko.com/api/v3/search?query=${encodeURIComponent(query)}`,
    );
    if (!res.ok) return [];
    const json = await res.json();
    const coins: Array<{ symbol: string; name: string }> = json?.coins ?? [];
    return coins.slice(0, 8).map((c) => ({
      symbol: c.symbol.toUpperCase(),
      name: c.name,
    }));
  } catch {
    return [];
  }
}
